name: Test ImageMagick

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-imagemagick:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Verify installation
        run: |
          echo "==> Checking available commands..."
          which convert || echo "convert not found"
          which magick || echo "magick not found"
          convert --version || echo "convert failed"
          magick --version || echo "magick failed"

      - name: Run simple convert test
        run: |
          echo "==> Creating test image..."
          convert -size 100x100 xc:red test.png || magick convert -size 100x100 xc:red test.png
          ls -l test.png
