name: Test ImageMagick

on:
  push:
    branches:
      - master   # 你可以改成测试分支
  workflow_dispatch:

jobs:
  test-imagemagick:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick ghostscript
          echo "==> Checking available ImageMagick commands..."
          which magick || echo "magick not found"
          magick --version || echo "magick command failed"

      - name: Run simple magick convert test
        run: |
          echo "==> Creating test image with magick..."
          magick convert -size 100x100 xc:red test.png
          ls -l test.png
